coverage:
  status:
    project:
      default:
		# auto will use main unless it's a branch of a branch
        target: auto
		# fail only above 1% decrease
        threshold: 1%
		# don't worry if there isn't a comparable report
        if_not_found: success
		# show new code line differential on PR, don't fail
        informational: true
