/// BEWARE: This file has been automatically generated by the `atspi-codegen` crate.
/// Any edits to this file will be overwritten by the next re-generation of this file.

use serde::{Serialize, Deserialize};
use enumflags2::bitflags;

pub trait Signal {
  const INTERFACE: &'static str;
}
#[bitflags]
#[repr(u32)]
#[derive(Clone, Copy, Debug, Serialize, Deserialize, Hash, Eq, PartialEq, Ord, PartialOrd)]
pub enum ObjectEvents {
	PropertyChange,
	BoundsChanged,
	LinkSelected,
	StateChanged,
	ChildrenChanged,
	VisibleDataChanged,
	SelectionChanged,
	ModelChanged,
	ActiveDescendantChanged,
	Announcement,
	AttributesChanged,
	RowInserted,
	RowReordered,
	RowDeleted,
	ColumnInserted,
	ColumnReordered,
	ColumnDeleted,
	TextBoundsChanged,
	TextSelectionChanged,
	TextChanged,
	TextAttributesChanged,
	TextCaretMoved,
}
impl Signal for ObjectEvents {
  const INTERFACE: &'static str = "org.a11y.atspi.Event.Object";
}

#[bitflags]
#[repr(u32)]
#[derive(Clone, Copy, Debug, Serialize, Deserialize, Hash, Eq, PartialEq, Ord, PartialOrd)]
pub enum WindowEvents {
	PropertyChange,
	Minimize,
	Maximize,
	Restore,
	Close,
	Create,
	Reparent,
	DesktopCreate,
	DesktopDestroy,
	Destroy,
	Activate,
	Deactivate,
	Raise,
	Lower,
	Move,
	Resize,
	Shade,
	UUshade,
	Restyle,
}
impl Signal for WindowEvents {
  const INTERFACE: &'static str = "org.a11y.atspi.Event.Window";
}

#[bitflags]
#[repr(u32)]
#[derive(Clone, Copy, Debug, Serialize, Deserialize, Hash, Eq, PartialEq, Ord, PartialOrd)]
pub enum MouseEvents {
	Abs,
	Rel,
	Button,
}
impl Signal for MouseEvents {
  const INTERFACE: &'static str = "org.a11y.atspi.Event.Mouse";
}

#[bitflags]
#[repr(u32)]
#[derive(Clone, Copy, Debug, Serialize, Deserialize, Hash, Eq, PartialEq, Ord, PartialOrd)]
pub enum KeyboardEvents {
	Modifiers,
}
impl Signal for KeyboardEvents {
  const INTERFACE: &'static str = "org.a11y.atspi.Event.Keyboard";
}

#[bitflags]
#[repr(u32)]
#[derive(Clone, Copy, Debug, Serialize, Deserialize, Hash, Eq, PartialEq, Ord, PartialOrd)]
pub enum TerminalEvents {
	LineChanged,
	ColumnCountChanged,
	LineCountChanged,
	ApplicationChanged,
	CharWidthChanged,
}
impl Signal for TerminalEvents {
  const INTERFACE: &'static str = "org.a11y.atspi.Event.Terminal";
}

#[bitflags]
#[repr(u32)]
#[derive(Clone, Copy, Debug, Serialize, Deserialize, Hash, Eq, PartialEq, Ord, PartialOrd)]
pub enum DocumentEvents {
	LoadComplete,
	Reload,
	LoadStopped,
	ContentChanged,
	AttributesChanged,
	PageChanged,
}
impl Signal for DocumentEvents {
  const INTERFACE: &'static str = "org.a11y.atspi.Event.Document";
}

#[bitflags]
#[repr(u32)]
#[derive(Clone, Copy, Debug, Serialize, Deserialize, Hash, Eq, PartialEq, Ord, PartialOrd)]
pub enum FocusEvents {
	Focus,
}
impl Signal for FocusEvents {
  const INTERFACE: &'static str = "org.a11y.atspi.Event.Focus";
}

#[bitflags]
#[repr(u32)]
#[derive(Clone, Copy, Debug, Serialize, Deserialize, Hash, Eq, PartialEq, Ord, PartialOrd)]
pub enum CacheEvents {
	AddAccessible,
	RemoveAccessible,
}
impl Signal for CacheEvents {
  const INTERFACE: &'static str = "org.a11y.atspi.Cache";
}

